[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sillyORM"
version = "1.1.0"
description = "an ORM library"
readme = "README.md"
requires-python = ">=3.11"
license = "LGPL-3.0-only"
license-files = ["LICENSE"]
dependencies = [
    "alembic>=1.15,<1.19",
    "sqlalchemy~=2.0.40",
]

[project.optional-dependencies]
dev = [
    "psycopg2", "pytest", "coverage", "pylint", "mypy", "black", "Sphinx",
]

[tool.setuptools]
packages = ["sillyorm"]
