import logging
from typing import TYPE_CHECKING
import sqlalchemy
import alembic.autogenerate
import alembic.operations

if TYPE_CHECKING:  # pragma: no cover
    from .registry import Registry

_logger = logging.getLogger(__name__)


def _dump_op(op: alembic.operations.MigrateOperation) -> str:
    attrs = {}
    for name in dir(op):
        # private
        if name.startswith("_"):
            continue
        value = getattr(op, name)
        if not callable(value):
            attrs[name] = value
    return f"{type(op).__name__}({', '.join([f'{k}={v}' for k, v in attrs.items()])})"


def _log_op(op: alembic.operations.MigrateOperation) -> None:
    _logger.debug("running alembic op: %s", _dump_op(op))


def _run(registry: "Registry") -> None:
    def _conn_init(conn: sqlalchemy.engine.Connection) -> None:
        if conn.dialect.name == "sqlite":
            conn.execute(sqlalchemy.text("PRAGMA foreign_keys=OFF"))

    def _conn_exit(conn: sqlalchemy.engine.Connection) -> None:
        if conn.dialect.name == "sqlite":
            conn.execute(sqlalchemy.text("PRAGMA foreign_keys=ON"))

    with registry.engine.begin() as conn:
        _conn_init(conn)
        # render_as_batch must be enable to change columns in SQLite
        render_as_batch = conn.dialect.name == "sqlite"
        mc = alembic.migration.MigrationContext.configure(
            conn,
            opts={
                "include_object": (
                    registry._table_cmp_should_include  # pylint: disable=protected-access
                ),
                "compare_server_default": True,
            },
        )
        migration_script = alembic.autogenerate.produce_migrations(mc, registry.metadata)
        ops_obj = alembic.operations.Operations(mc)
        if migration_script.upgrade_ops is None:
            _conn_exit(conn)
            return
        for op in migration_script.upgrade_ops.ops:
            if isinstance(op, alembic.operations.ops.ModifyTableOps):
                if render_as_batch:
                    with ops_obj.batch_alter_table(op.table_name, schema=op.schema) as batch_op:
                        for sub_op in op.ops:
                            _log_op(sub_op)
                            batch_op.invoke(sub_op)
                else:
                    for sub_op in op.ops:
                        _log_op(sub_op)
                        ops_obj.invoke(sub_op)
            else:
                _log_op(op)
                ops_obj.invoke(op)
        _conn_exit(conn)


def run(registry: "Registry") -> None:
    """
    Given a registry object, check the difference between the
    registry metadata and the active DB, and apply migrations
    generated by alembic to get the DB into the correct state.

    This may cause data loss
    """

    # ensure we don't have any open connections left
    registry.engine.dispose()

    _run(registry)

    # ensure none of of the migration connections get reused
    registry.engine.dispose()
