name: Python typecheck

on: [push]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install mypy
        run: pip install mypy
      - name: Install dependencies
        run: pip install alembic sqlalchemy pytest
      - name: run typecheck
        run: make typecheck
